### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by kaustubh2332** [rubenIng93/mmwave-decoder#2]
I have been assigned a task under a statement :- " Calibration of mm wave sensor for accurate data reading " . I am using AWR1843 mm wave sensor and I have captured the raw data with mm wave demo visualizer and used your code to convert the DAT file to CSV file . Do you have any code which will help in calibration of this raw data ? As I am unable to find ant repositories for this . If you have any code or have any idea how to do this task would be great help !

**Comment by rubenIng93** [comment]
Sorry, unfortunately I am not able to help you with your task.
